### PR TITLE
bug: update baseURL for docs

### PR DESCRIPTION
**Pull request by djzager**

### CODE REVIEW

**Comment by kaovilai** [comment]
Why is baseURL needed? Can we use relative url instead?
https://github.com/vmware-tanzu/velero/pull/4583/files works just fine without baseUrl

**Comment by kaovilai** [comment]
Using relative path is beautiful in the world of static sites. So hyperlinks works regardless of baseDomain

PS. Checkout  [velero.tig.pw](https://velero.tig.pw) :P

**Review by jmontleon — APPROVED** [review]
ACK

**Review by JaydipGabani — APPROVED** [review]

**Comment by djzager** [comment]
took longer than I would have liked but I finally updated based on @kaovilai 's comment :sunglasses:

**Pull request merged**
